### PR TITLE
Ros integration

### PR DESCRIPTION
**Pull request by yellak**
This pull request creates a ROS integration with HMRSim

### CODE REVIEW

**Comment by gabrielsr** [comment]
We need a description of how to execute a simulation with ROS, in the wiki or a readme.md file.

**Comment by yellak** [comment]
Working on it...

**Comment by yellak** [comment]
@gabrielsr, created.

**Comment by gabrielsr** [comment]
I suggest rename the MoveBaseSystem to Nav2System

**Pull request merged**
